title: Glauca Digital
email: info@glauca.digital
baseurl: ""
url: "https://glauca.digital"
twitter: "@GlaucaDigital"
plugins:
  - jekyll-feed
feed:
  categories:
    - blog

exclude:
  - "deploy.sh"
include:
  - ".well-known"

