title: Glauca Digital
email: info@glauca.digital
baseurl: ""
url: "https://glauca.digital"
twitter: "@GlaucaDigital"
plugins:
  - jekyll-feed
  - jekyll-get-json
feed:
  categories:
    - blog

exclude:
  - "deploy.sh"
include:
  - ".well-known"

jekyll_get_json:
  - data: tlds
    json: "https://domains.glauca.digital/data/tlds/"
